src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=13)
     */
    private $barcode;


    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $stock;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $entries;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $exits;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $min_alert;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $max_alert;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $ean13;

    /**
     * @ORM\ManyToOne(targetEntity=Provider::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $provider;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBarcode(): ?string
    {
        return $this->barcode;
    }

    public function setBarcode(string $barcode): self
    {
        $this->barcode = $barcode;

        return $this;
    }


    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(?int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getEntries(): ?int
    {
        return $this->entries;
    }

    public function setEntries(?int $entries): self
    {
        $this->entries = $entries;

        return $this;
    }

    public function getExits(): ?int
    {
        return $this->exits;
    }

    public function setExits(?int $exits): self
    {
        $this->exits = $exits;

        return $this;
    }

    public function getMinAlert(): ?int
    {
        return $this->min_alert;
    }

    public function setMinAlert(?int $min_alert): self
    {
        $this->min_alert = $min_alert;

        return $this;
    }

    public function getMaxAlert(): ?int
    {
        return $this->max_alert;
    }

    public function setMaxAlert(?int $max_alert): self
    {
        $this->max_alert = $max_alert;

        return $this;
    }

    public function getEan13(): ?string
    {
        return $this->ean13;
    }

    public function setEan13(?string $ean13): self
    {
        $this->ean13 = $ean13;

        return $this;
    }

    public function getProvider(): ?Provider
    {
        return $this->provider;
    }

    public function setProvider(?Provider $provider): self
    {
        $this->provider = $provider;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use App\Entity\Provider;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Libellé',

            ])
            ->add('barcode', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'maxlength' => 12
                ],
                'label' => 'Code-barre',

            ])
            ->add('provider', EntityType::class, [
                'class' => Provider::class,
                'choice_label' => 'name',
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Fournisseur',

            ])
            ->add('stock', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Stock',
            ])
            ->add('min_alert', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Seuil d\'alerte minimum',
            ])
            ->add('max_alert', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Seuil d\'alerte maximum',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Flux;
use App\Entity\Product;
use App\Entity\User;
use App\Form\ESType;
use App\Form\ProductType;
use App\Repository\FluxRepository;
use App\Repository\ProductRepository;
use App\Service\Ean13Generator;
use CodeItNow\BarcodeBundle\Utils\BarcodeGenerator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

/**
 * @Route("/product")
 */
class ProductController extends AbstractController
{
    /**
     * @Route("/", name="product_index", methods={"GET"})
     * @param ProductRepository $productRepository
     * @param AuthorizationCheckerInterface $authChecker
     * @return Response
     */
    public function index(ProductRepository $productRepository,  AuthorizationCheckerInterface $authChecker): Response
    {

        $barcode = new BarcodeGenerator();

        $products = $productRepository->findAll();
        foreach($products as $product){
            $barcode->setText($product->getBarcode());
            $barcode->setType(BarcodeGenerator::Ean13);
            $barcode->setScale(2);
            $barcode->setThickness(25);
            $barcode->setFontSize(10);
            $product->setEan13($barcode->generate());

            if (empty($product->getStock())){
                $product->setStock(0);
            }
            if (empty($product->getEntries())){
                $product->setEntries(0);
            }
            if (empty($product->getExits())){
                $product->setExits(0);
            }

        }

        if ($authChecker->isGranted('ROLE_ADMIN')){
            return $this->render('product/index.html.twig', [
                'products' => $products,
                'enterprise' => 'Eiffage',
                'actions' => true
            ]);
        } else if ($authChecker->isGranted('ROLE_USER') || $authChecker->isGranted('ROLE_MAG')){
            return $this->render('product/index.html.twig', [
                'products' => $products,
                'enterprise' => 'Eiffage',
                'actions' => false
            ]);
        }
    }

    /**
     * @Route("/entries_exits", name="product_es", methods={"GET", "POST"})
     * @param Request $request
     * @param ProductRepository $productRepository
     * @param Flux $flux
     * @return Response
     */
    public function es(Request $request, ProductRepository $productRepository): Response
    {
        $form = $this->createForm(ESType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $formValues = $request->request->get('es');
            $product = $productRepository->find($formValues['id']);
            $dateTimeImmutable = new \DateTime('now');
            $user = $this->getUser();
            $flux = new Flux();
            if ($formValues['flow_type'] === "entry"){
                $product->setEntries($product->getEntries() + $formValues['quantity']);
                $product->setStock($product->getStock() + $formValues['quantity']);
                $flux->setUser($user);
                $flux->setBarcode($formValues['barcode']);
                $flux->setDatetime($dateTimeImmutable);
                $flux->setName($product->getName());
                $flux->setQuantity($formValues['quantity']);
                $flux->setType('Entrée');
            } else if ($formValues['flow_type'] === 'exit'){
                $product->setExits($product->getExits() + $formValues['quantity']);
                $product->setStock($product->getStock() - $formValues['quantity']);
                $flux->setUser($user);
                $flux->setBarcode($formValues['barcode']);
                $flux->setDatetime($dateTimeImmutable);
                $flux->setName($product->getName());
                $flux->setQuantity($formValues['quantity']);
                $flux->setType('Sortie');
            }

            $this->getDoctrine()->getManager()->persist($product);
            $this->getDoctrine()->getManager()->persist($flux);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('product_index');
        }

        return $this->render('product/es.html.twig', [
            'form' => $form->createView(),
            'enterprise' => 'Eiffage',
        ]);
    }

    /**
     * @Route("/new", name="product_new", methods={"GET","POST"})
     * @param Request $request
     * @param Flux $flux
     * @return Response
     */

    public function new(Request $request): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($product);
            $entityManager->flush();

            return $this->redirectToRoute('product_index');
        }

        return $this->render('product/new.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
            'enterprise' => 'Eiffage'
        ]);
    }

    /**
     * @Route("/search", name="product_search", methods={"POST", "GET"})
     * @param Request $request
     * @param ProductRepository $productRepository
     * @return JsonResponse
     */
    public function searchByBarcode(Request $request, ProductRepository $productRepository): JsonResponse
    {
        if ($request->isXmlHttpRequest()){
            $barcode = $request->request->get('searchValue');
            $product = $productRepository->findOneBy(['barcode' => $barcode]);
            $response = new JsonResponse([
                'name' => $product->getName(),
                'id' => $product->getId()
            ]);
            $response->headers->set('Content-Type', 'application/json');
            $response->headers->set('Access-Control-Allow-Origin', '*');

            return $response;
        }
    }

    /**
     * @Route("/generate_barcode", name="generate_barcode", methods={"POST", "GET"})
     * @param Request $request
     * @param ProductRepository $productRepository
     * @param Ean13Generator $ean13Generator
     * @return Response
     */
    public function generateBarcode(Request $request, ProductRepository $productRepository, Ean13Generator $ean13Generator): Response
    {
        if ($request->isXmlHttpRequest()){
            $barcode = new BarcodeGenerator();
            $code = false;
            if ($request->request->get('isEdit')){
                $barcode->setText($request->request->get('searchValue'));
            } else {
                $code = $ean13Generator->generateEan13($productRepository);
                $barcode->setText($code);
            }
            $barcode->setType(BarcodeGenerator::Ean13);
            $barcode->setScale(2);
            $barcode->setThickness(25);
            $barcode->setFontSize(10);
            $response = new JsonResponse([
                'image' => '<p>EAN13 : <img src="data:image/png;base64,' . $barcode->generate() . '"/></p>',
                'code' => $code
            ]);
            $response->headers->set('Content-Type', 'application/json');
            $response->headers->set('Access-Control-Allow-Origin', '*');

            return $response;
        }
    }


    /**
     * @Route("/{id}", name="product_show", methods={"GET"})
     */
    public function show(Product $product): Response
    {
        return $this->render('product/show.html.twig', [
            'product' => $product,
            'enterprise' => 'Eiffage'
        ]);
    }

    /**
     * @Route("/{id}/edit", name="product_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Product $product): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('product_index');
        }
        return $this->render('product/edit.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
            'enterprise' => 'Eiffage'
        ]);
    }

    /**
     * @Route("/{id}", name="product_delete", methods={"POST"})
     */
    public function delete(Request $request, Product $product): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('product_index');
    }

}

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('product_delete', {'id': product.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce produit ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
        <button class="btn">Supprimer</button>
</form>

templates/product/_es-form.html.twig
{{ form_start(form) }}
<div class="row">
    <div class="col-md-4">
        {{ form_row(form.barcode) }}
    </div>
        {{ form_row(form.id) }}
    <div class="col-md-4">
        <label for="es_quantity">Quantité</label>
        <input type="number" id="es_quantity" name="es[quantity]" required="required" class="form-control" min="0">
    </div>
    <div id="searchResults"></div>
    <div class="col-md-12">
        <div class="form-check form-check-radio form-check-inline" id="es_flow_type">
            <label class="form-check-label" for="es_flow_type_entry">
                <input class="form-check-input" type="radio" name="es[flow_type]" id="es_flow_type_entry" value="entry"> Entrée
                <span class="form-check-sign"></span>
            </label>
        </div>
        <div class="form-check form-check-radio form-check-inline">
            <label class="form-check-label" for="es_flow_type_exit">
                <input class="form-check-input" type="radio" name="es[flow_type]" id="es_flow_type_exit" value="exit"> Sortie
                <span class="form-check-sign"></span>
            </label>
        </div>
    </div>
</div>

    <button class="btn" id="es_button_send" disabled>{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/product/_form.html.twig
{{ form_start(form) }}
<div class="row">
    <div class="col-md-3">
        {{ form_row(form.name) }}
    </div>
    <div class="col-md-3">
        {{ form_row(form.barcode) }}
    </div>
    <div class="col-md-3" id="generated_barcode">
        <p>Code-barre</p>
    </div>
    <div class="col-md-3">
        <button type="button" class="btn" onclick="generateBarcode()">Générer</button>
    </div>
    <div class="col-md-3">
        {{ form_row(form.provider) }}
    </div>
    <div class="col-md-3">
        {{ form_row(form.stock) }}
    </div>
    <div class="col-md-3">
        {{ form_row(form.min_alert) }}
    </div>
    <div class="col-md-3">
        {{ form_row(form.max_alert) }}
    </div>
</div>

    <button class="btn">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/product/edit.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Modifier un produit{% endblock %}

{% block body %}
<div class="content">
    <h1 class="text-center title">Gestion des produits</h1>
    <div class="row">
        <div class="col-lg-8 ml-auto mr-auto">
            <div class="row">
                <h1>Modification d'un produit</h1>

                {{ include('product/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
                <div class="col-md-3">
                    {{ include('product/_delete_form.html.twig') }}
                </div>
                <div class="col-md-12">
                    <a href="{{ path('product_index') }}">retour à la liste</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/product/es.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Gestion des entrées/sorties{% endblock %}

{% block body %}
<div class="content">
    <h1 class="text-center title">Gestion des entrées/sorties</h1>
    <div class="row">
        <div class="col-lg-8 ml-auto mr-auto">
            <div class="row">
                {{ include('product/_es-form.html.twig', {'button_label': 'Mettre à jour'}) }}
                <div class="col-md-12">
                    <a href="{{ path('product_index') }}">retour à la liste</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/product/index.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Gestion des produits{% endblock %}

{% block body %}
    <div class="content">
        <h1 class="text-center title">Gestion des produits</h1>
        <div class="row">
            <div class="col-lg-12 ml-auto mr-auto">
                <div class="row">
                    <table class="table">
                        <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th>Nom</th>
                            <th>Code barre</th>
                            <th>EAN13</th>
                            <th>Fournisseur</th>
                            <th>Stock</th>
                            <th>Entrées</th>
                            <th>Sorties</th>
                            <th>Alerte</th>
                            <th>Min. Alerts</th>
                            <th>Max. Alerts</th>
                            {% if  actions != false %}
                            <th class="text-center">Actions</th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody>
                            {% for product in products %}
                        <tr>
                            <td>{{ product.id }}</td>
                            <td>{{ product.name }}</td>
                            <td>{{ product.barcode }}</td>
                            <td><img src="data:image/png;base64,{{ product.ean13 }}" /></td>
                            <td>{{ product.provider.name }}</td>
                            <td>{{ product.stock }}</td>
                            <td>{{ product.entries }}</td>
                            <td>{{ product.exits }}</td>
                            {% if product.stock < product.minAlert %}
                            <td class="alert-warning text-center">PAS ASSEZ DE STOCK</td>
                                {% elseif product.stock > product.maxAlert %}
                            <td class="alert-danger text-center">TROP DE STOCK</td>
                                {% else %}
                            <td class="alert-success text-center">BON</td>
                                {% endif %}
                            <td>{{ product.minAlert }}</td>
                            <td>{{ product.maxAlert }}</td>
                            {% if actions != false %}
                            <td class="td-actions text-center">
                                <button type="button" onclick="location.href='{{ path('product_show', {'id': product.id}) }}'" rel="tooltip" class="btn btn-info btn-sm btn-round btn-icon">
                                    <i class="tim-icons icon-zoom-split"></i>
                                </button>
                                <button type="button" onclick="location.href='{{ path('product_edit', {'id': product.id}) }}'" rel="tooltip" class="btn btn-success btn-sm btn-round btn-icon">
                                    <i class="tim-icons icon-settings"></i>
                                </button>
                                <button type="button" onclick="location.href='{{ path('product_delete', {'id': product.id}) }}'" rel="tooltip" class="btn btn-danger btn-sm btn-round btn-icon">
                                    <i class="tim-icons icon-simple-remove"></i>
                                </button>
                            </td>
                            {% endif %}
                        </tr>
                        {% else %}
                            <tr>
                                <td colspan="10">Aucun produit répertorié en base de données.</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                    <a href="{{ path('product_new') }}">Ajouter un produit</a>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/product/new.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Nouveau produit{% endblock %}

{% block body %}
<div class="content">
    <div class="row">
        <div class="col-lg-8 ml-auto mr-auto">
                {{ include('product/_form.html.twig') }}
        </div>
    </div>
</div>
    <a href="{{ path('product_index') }}">back to list</a>
{% endblock %}

templates/product/show.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
<div class="content">
    <h1 class="text-center title">Gestion des produits</h1>
    <div class="row">
        <div class="col-lg-8 ml-auto mr-auto">
            <div class="row">
                <h1>Product</h1>

                <table class="table">
                    <tbody>
                        <tr>
                            <th>Id</th>
                            <td>{{ product.id }}</td>
                        </tr>
                        <tr>
                            <th>Name</th>
                            <td>{{ product.name }}</td>
                        </tr>
                        <tr>
                            <th>Barcode</th>
                            <td>{{ product.barcode }}</td>
                        </tr>
                        <tr>
                            <th>Provider</th>
                            <td>{{ product.provider }}</td>
                        </tr>
                        <tr>
                            <th>Stock</th>
                            <td>{{ product.stock }}</td>
                        </tr>
                        <tr>
                            <th>Entries</th>
                            <td>{{ product.entries }}</td>
                        </tr>
                        <tr>
                            <th>Exits</th>
                            <td>{{ product.exits }}</td>
                        </tr>
                        <tr>
                            <th>Min_alert</th>
                            <td>{{ product.minAlert }}</td>
                        </tr>
                        <tr>
                            <th>Max_alert</th>
                            <td>{{ product.maxAlert }}</td>
                        </tr>
                    </tbody>
                </table>

                <a href="{{ path('product_index') }}">back to list</a>

                <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>

                {{ include('product/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
</div>
{% endblock %}